version: "2"
linters:
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - zerologlint
  settings:
    goconst:
      min-occurrences: 3
    staticcheck:
      checks:
        - all
        - "-ST1005" # disable error string should not be capitalized
        - "-ST1000" # disable at least one file in a package should have a package comment
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    rules:
      - path: export_test.go
        linters:
          - unused
formatters:
  enable:
    - gofmt
    - goimports
