name: BDD tests

on:
  - push
  - pull_request

jobs:
  bdd:
    runs-on: ubuntu-latest
    name: BDD for Go ${{ matrix.go-version}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Build project
        run: make build
      - name: Retrieve Docker compose file
        run: wget -O docker-compose.yml https://raw.githubusercontent.com/RedHatInsights/insights-behavioral-spec/main/docker-compose.yml
      - name: Retrieve BDD runner
        run: wget -O bdd_runner.sh https://raw.githubusercontent.com/RedHatInsights/insights-behavioral-spec/main/run_in_docker.sh && chmod +x bdd_runner.sh
      - name: Run BDD
        run: ./bdd_runner.sh aggregator-mock-tests .
